### ISSUE TITLE
CMS questions / proposal

### ISSUE THREAD

**Issue by vitordino** [LeKoArts/gatsby-starter-portfolio-emilia#1]
Hi LeKoArts,

first of all, congratulations on this nice repo :tada:

are you planning on adding any CMS on this one,
or is without one on purpose (for more flexibility)?

I may use this project in the next few months,
and if I do so, I'll probably use Netlify CMS,
are you interested on a PR, or maybe branch with it?

**Comment by vitordino** [comment]
just saw [cethy's branch](https://github.com/Cethy/gatsby-starter-portfolio-emilia/tree/netlify-cms) on this, i'll close this and follow theirs solution for now.

**Comment by LeKoArts** [comment]
@vitordino Hi!
Thanks for the kind words. You're right, I keep all my starters as simple as possible on purpose (for more flexibility & the user doesn't have to change too much on some of my opinionated choices).
