### ISSUE TITLE
Shows blank page in Edge and IE11

### ISSUE THREAD

**Issue by jonnysmillie** [LekoArts/gatsby-starter-portfolio-emilia#5]
Hey, love this starter but used it and then found that nothing displays in IE11 and Edge browsers. Wondered if you were aware and if there was an easy fix you know of? Thanks

**Comment by LekoArts** [comment]
You need to polyfill the browser support :)
https://react-spring.surge.sh/gotchas#browser-support
https://www.gatsbyjs.org/docs/browser-support/
