### ISSUE TITLE
S3 Integration?

### ISSUE THREAD

**Issue by mailtokamalnayan** [LekoArts/gatsby-starter-portfolio-emilia#54]
I love this theme and I've been using it for one of my projects. However, when there're more photos (800+) the project repository becomes quite bulky.

I was wondering if we can extend this wonderful theme to support S3. I was taking a look at the [gatsby-source-s3-image](https://www.gatsbyjs.org/packages/gatsby-source-s3-image/?=exif) and it has slightly similar use case.

Query the Bucket --> List all the folders as projects -> Show images inside the folder

Even though images are hosted remotely, we might be able to utilise the `gatsby-image` functionalities through plugins like [gatsby-plugin-remote-images](https://www.gatsbyjs.org/packages/gatsby-plugin-remote-images/?=remote)

**Comment by LekoArts** [comment]
Hey, I'm pretty sure that you'll be able to use S3 with this starter. You should also have a look into the [Asset Prefix](https://www.gatsbyjs.org/docs/asset-prefix/) that recently got added :)
